name: ytdl
description: "Frontend for ytdl."
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.8.1
  
dependencies:
  flutter:
    sdk: flutter

  # cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  material_symbols_icons: ^4.2815.1
  path_provider: ^2.1.5
  path: ^1.9.1
  logger: ^2.6.0
  provider: ^6.1.5
  http: ^1.4.0
  audioplayers: ^6.5.0
  # ffmpeg_kit_flutter_new: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
 
